// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/main/java/src/scanner.lex

package src;


@SuppressWarnings("fallthrough")
class AnalisadorLexico {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\2\1\1\2\2\1\22\0\1\1\1\0\1\3"+
    "\2\0\1\4\2\0\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\0\1\13\12\14\1\15\1\16\1\17\1\20"+
    "\1\21\2\0\32\22\6\0\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\2\22\1\34\1\35"+
    "\1\36\1\37\1\40\1\22\1\41\1\42\1\43\2\22"+
    "\1\44\3\22\12\0\1\2\u01a2\0\2\2\326\0\u0100\2";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\2\1\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\1\1\14\1\15"+
    "\1\1\1\16\16\17\1\0\1\20\1\0\1\21\1\22"+
    "\1\23\1\24\1\25\1\26\3\17\1\27\3\17\1\30"+
    "\3\17\1\31\3\17\1\32\2\17\1\33\3\17\1\34"+
    "\1\35\1\17\1\36\1\37\10\17\1\40\2\17\1\41"+
    "\1\42\2\17\1\43\4\17\1\44\1\45\4\17\1\46"+
    "\1\47\1\50\1\51";

  private static int [] zzUnpackAction() {
    int [] result = new int[99];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\45\0\45\0\45\0\112\0\157\0\45\0\45"+
    "\0\45\0\45\0\45\0\45\0\45\0\224\0\271\0\45"+
    "\0\336\0\u0103\0\u0128\0\u014d\0\u0172\0\u0197\0\u01bc\0\u01e1"+
    "\0\u0206\0\u022b\0\u0250\0\u0275\0\u029a\0\u02bf\0\u02e4\0\u0309"+
    "\0\u032e\0\112\0\45\0\157\0\157\0\45\0\45\0\45"+
    "\0\45\0\45\0\u0353\0\u0378\0\u039d\0\u014d\0\u03c2\0\u03e7"+
    "\0\u040c\0\u014d\0\u0431\0\u0456\0\u047b\0\u014d\0\u04a0\0\u04c5"+
    "\0\u04ea\0\u014d\0\u050f\0\u0534\0\u014d\0\u0559\0\u057e\0\u05a3"+
    "\0\u014d\0\u014d\0\u05c8\0\u014d\0\u014d\0\u05ed\0\u0612\0\u0637"+
    "\0\u065c\0\u0681\0\u06a6\0\u06cb\0\u06f0\0\u014d\0\u0715\0\u073a"+
    "\0\u014d\0\u014d\0\u075f\0\u0784\0\u014d\0\u07a9\0\u07ce\0\u07f3"+
    "\0\u0818\0\u014d\0\u014d\0\u083d\0\u0862\0\u0887\0\u08ac\0\u014d"+
    "\0\u014d\0\u014d\0\u014d";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[99];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\24\1\27\1\30"+
    "\1\31\2\24\1\32\1\24\1\33\1\34\1\35\1\36"+
    "\1\37\1\24\1\40\1\41\45\0\3\42\1\43\41\42"+
    "\4\44\1\45\40\44\14\0\1\16\50\0\1\46\44\0"+
    "\1\47\1\50\43\0\1\51\44\0\1\52\40\0\1\24"+
    "\5\0\23\24\14\0\1\24\5\0\14\24\1\53\6\24"+
    "\14\0\1\24\5\0\5\24\1\54\15\24\14\0\1\24"+
    "\5\0\5\24\1\55\7\24\1\56\5\24\14\0\1\24"+
    "\5\0\12\24\1\57\1\24\1\60\6\24\14\0\1\24"+
    "\5\0\15\24\1\61\5\24\14\0\1\24\5\0\6\24"+
    "\1\62\5\24\1\63\6\24\14\0\1\24\5\0\15\24"+
    "\1\64\5\24\14\0\1\24\5\0\15\24\1\65\5\24"+
    "\14\0\1\24\5\0\17\24\1\66\3\24\14\0\1\24"+
    "\5\0\17\24\1\67\3\24\14\0\1\24\5\0\5\24"+
    "\1\70\15\24\14\0\1\24\5\0\10\24\1\71\4\24"+
    "\1\72\5\24\14\0\1\24\5\0\10\24\1\73\6\24"+
    "\1\74\3\24\14\0\1\24\5\0\4\24\1\75\16\24"+
    "\14\0\1\24\5\0\7\24\1\76\13\24\14\0\1\24"+
    "\5\0\3\24\1\77\17\24\14\0\1\24\5\0\20\24"+
    "\1\100\2\24\14\0\1\24\5\0\4\24\1\101\16\24"+
    "\14\0\1\24\5\0\17\24\1\102\3\24\14\0\1\24"+
    "\5\0\21\24\1\103\1\24\14\0\1\24\5\0\4\24"+
    "\1\104\16\24\14\0\1\24\5\0\21\24\1\105\1\24"+
    "\14\0\1\24\5\0\15\24\1\106\5\24\14\0\1\24"+
    "\5\0\1\24\1\107\21\24\14\0\1\24\5\0\5\24"+
    "\1\110\15\24\14\0\1\24\5\0\11\24\1\111\11\24"+
    "\14\0\1\24\5\0\11\24\1\112\11\24\14\0\1\24"+
    "\5\0\11\24\1\113\11\24\14\0\1\24\5\0\11\24"+
    "\1\114\1\115\10\24\14\0\1\24\5\0\5\24\1\116"+
    "\15\24\14\0\1\24\5\0\5\24\1\117\15\24\14\0"+
    "\1\24\5\0\7\24\1\120\13\24\14\0\1\24\5\0"+
    "\4\24\1\121\16\24\14\0\1\24\5\0\14\24\1\122"+
    "\6\24\14\0\1\24\5\0\12\24\1\123\10\24\14\0"+
    "\1\24\5\0\21\24\1\124\1\24\14\0\1\24\5\0"+
    "\14\24\1\125\6\24\14\0\1\24\5\0\13\24\1\126"+
    "\7\24\14\0\1\24\5\0\1\24\1\127\21\24\14\0"+
    "\1\24\5\0\7\24\1\130\13\24\14\0\1\24\5\0"+
    "\17\24\1\131\3\24\14\0\1\24\5\0\5\24\1\132"+
    "\15\24\14\0\1\24\5\0\5\24\1\133\15\24\14\0"+
    "\1\24\5\0\1\24\1\134\21\24\14\0\1\24\5\0"+
    "\17\24\1\135\3\24\14\0\1\24\5\0\5\24\1\136"+
    "\15\24\14\0\1\24\5\0\1\24\1\137\21\24\14\0"+
    "\1\24\5\0\12\24\1\140\10\24\14\0\1\24\5\0"+
    "\5\24\1\141\15\24\14\0\1\24\5\0\17\24\1\142"+
    "\3\24\14\0\1\24\5\0\13\24\1\143\7\24";

  private static int [] zzUnpacktrans() {
    int [] result = new int[2257];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\3\11\2\1\7\11\2\1\1\11\21\1\1\0"+
    "\1\11\1\0\1\1\5\11\71\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[99];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
      TabelaDeSimbolos tabela = new TabelaDeSimbolos();

      private void addToken(TiposDeToken type,String value) {
        tabela.novaEntrada(type,value,yycolumn, yyline);
      }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  AnalisadorLexico(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public int yylex() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return YYEOF;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { System.out.print("Caractere invalido" + yytext() + "\n");
            }
          // fall through
          case 42: break;
          case 2:
            { 
            }
          // fall through
          case 43: break;
          case 3:
            { System.out.print(yytext());
            }
          // fall through
          case 44: break;
          case 4:
            { addToken(TiposDeToken.LEFT_PARENTHESIS, yytext()); System.out.print("Operador "+ yytext() + "\n");
            }
          // fall through
          case 45: break;
          case 5:
            { addToken(TiposDeToken.RIGHT_PARENTHESIS, yytext()); System.out.print("Operador "+ yytext() + "\n");
            }
          // fall through
          case 46: break;
          case 6:
            { addToken(TiposDeToken.OPERADOR_MULT, yytext()); System.out.print("Operador "+ yytext() + "\n");
            }
          // fall through
          case 47: break;
          case 7:
            { addToken(TiposDeToken.OPERADOR_ADD, yytext()); System.out.print("Operador "+ yytext() + "\n");
            }
          // fall through
          case 48: break;
          case 8:
            { addToken(TiposDeToken.COMMA, yytext()); System.out.print("Operador "+ yytext() + "\n");
            }
          // fall through
          case 49: break;
          case 9:
            { addToken(TiposDeToken.OPERADOR_MINUS, yytext()); System.out.print("Operador "+ yytext() + "\n");
            }
          // fall through
          case 50: break;
          case 10:
            { addToken(TiposDeToken.OPERADOR_PART, yytext()); System.out.print("Operador "+ yytext() + "\n");
            }
          // fall through
          case 51: break;
          case 11:
            { addToken(TiposDeToken.CONSTANT, yytext()); System.out.print("Constante "+ yytext() + "\n");
            }
          // fall through
          case 52: break;
          case 12:
            { addToken(TiposDeToken.SEMICOLON, yytext()); System.out.print("Ponto e vírgula \n");
            }
          // fall through
          case 53: break;
          case 13:
            { addToken(TiposDeToken.OPERADOR_LESS, yytext()); System.out.print("Operador "+ yytext() + "\n");
            }
          // fall through
          case 54: break;
          case 14:
            { addToken(TiposDeToken.OPERADOR_GREAT, yytext()); System.out.print("Operador "+ yytext() + "\n");
            }
          // fall through
          case 55: break;
          case 15:
            { addToken(TiposDeToken.IDENTIFICADOR, yytext()); System.out.print("Identificador "+ yytext() + "\n");
            }
          // fall through
          case 56: break;
          case 16:
            { addToken(TiposDeToken.LITERAL, yytext()); System.out.print("Literal "+ yytext() + "\n");
            }
          // fall through
          case 57: break;
          case 17:
            { System.out.print("Comentário "+ yytext() + "\n");
            }
          // fall through
          case 58: break;
          case 18:
            { addToken(TiposDeToken.OPERADOR_ASSIGN, yytext()); System.out.print("Operador "+ yytext() + "\n");
            }
          // fall through
          case 59: break;
          case 19:
            { addToken(TiposDeToken.OPERADOR_LESSEQUAL, yytext()); System.out.print("Operador "+ yytext() + "\n");
            }
          // fall through
          case 60: break;
          case 20:
            { addToken(TiposDeToken.OPERADOR_DIFFERENT, yytext()); System.out.print("Operador "+ yytext() + "\n");
            }
          // fall through
          case 61: break;
          case 21:
            { addToken(TiposDeToken.OPERADOR_EQUAL, yytext()); System.out.print("Operador "+ yytext() + "\n");
            }
          // fall through
          case 62: break;
          case 22:
            { addToken(TiposDeToken.OPERADOR_GREATEQUAL, yytext()); System.out.print("Operador "+ yytext() + "\n");
            }
          // fall through
          case 63: break;
          case 23:
            { addToken(TiposDeToken.PALAVRA_RESERVADA_DO, yytext()); System.out.print("Palavra Reservada "+ yytext() + "\n");
            }
          // fall through
          case 64: break;
          case 24:
            { addToken(TiposDeToken.PALAVRA_RESERVADA_IF, yytext()); System.out.print("Palavra Reservada "+ yytext() + "\n");
            }
          // fall through
          case 65: break;
          case 25:
            { addToken(TiposDeToken.PALAVRA_RESERVADA_OR, yytext()); System.out.print("Palavra Reservada "+ yytext() + "\n");
            }
          // fall through
          case 66: break;
          case 26:
            { addToken(TiposDeToken.PALAVRA_RESERVADA_TO, yytext()); System.out.print("Palavra Reservada "+ yytext() + "\n");
            }
          // fall through
          case 67: break;
          case 27:
            { addToken(TiposDeToken.PALAVRA_RESERVADA_AND, yytext()); System.out.print("Palavra Reservada "+ yytext() + "\n");
            }
          // fall through
          case 68: break;
          case 28:
            { addToken(TiposDeToken.PALAVRA_RESERVADA_END, yytext()); System.out.print("Palavra Reservada "+ yytext() + "\n");
            }
          // fall through
          case 69: break;
          case 29:
            { addToken(TiposDeToken.PALAVRA_RESERVADA_FOR, yytext()); System.out.print("Palavra Reservada "+ yytext() + "\n");
            }
          // fall through
          case 70: break;
          case 30:
            { addToken(TiposDeToken.PALAVRA_RESERVADA_MOD, yytext()); System.out.print("Palavra Reservada "+ yytext() + "\n");
            }
          // fall through
          case 71: break;
          case 31:
            { addToken(TiposDeToken.PALAVRA_RESERVADA_NOT, yytext()); System.out.print("Palavra Reservada "+ yytext() + "\n");
            }
          // fall through
          case 72: break;
          case 32:
            { addToken(TiposDeToken.PALAVRA_RESERVADA_ELSE, yytext()); System.out.print("Palavra Reservada "+ yytext() + "\n");
            }
          // fall through
          case 73: break;
          case 33:
            { addToken(TiposDeToken.PALAVRA_RESERVADA_READ, yytext()); System.out.print("Palavra Reservada "+ yytext() + "\n");
            }
          // fall through
          case 74: break;
          case 34:
            { addToken(TiposDeToken.PALAVRA_RESERVADA_THEN, yytext()); System.out.print("Palavra Reservada "+ yytext() + "\n");
            }
          // fall through
          case 75: break;
          case 35:
            { addToken(TiposDeToken.PALAVRA_RESERVADA_BEGIN, yytext()); System.out.print("Palavra Reservada "+ yytext() + "\n");
            }
          // fall through
          case 76: break;
          case 36:
            { addToken(TiposDeToken.PALAVRA_RESERVADA_WHILE, yytext()); System.out.print("Palavra Reservada "+ yytext() + "\n");
            }
          // fall through
          case 77: break;
          case 37:
            { addToken(TiposDeToken.PALAVRA_RESERVADA_WRITE, yytext()); System.out.print("Palavra Reservada "+ yytext() + "\n");
            }
          // fall through
          case 78: break;
          case 38:
            { addToken(TiposDeToken.PALAVRA_RESERVADA_DECIMAL, yytext()); System.out.print("Palavra Reservada "+ yytext() + "\n");
            }
          // fall through
          case 79: break;
          case 39:
            { addToken(TiposDeToken.PALAVRA_RESERVADA_DECLARE, yytext()); System.out.print("Palavra Reservada "+ yytext() + "\n");
            }
          // fall through
          case 80: break;
          case 40:
            { addToken(TiposDeToken.PALAVRA_RESERVADA_INTEGER, yytext()); System.out.print("Palavra Reservada "+ yytext() + "\n");
            }
          // fall through
          case 81: break;
          case 41:
            { addToken(TiposDeToken.PALAVRA_RESERVADA_PROGRAM, yytext()); System.out.print("Palavra Reservada "+ yytext() + "\n");
            }
          // fall through
          case 82: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String[] argv) {
    if (argv.length == 0) {
      System.out.println("Usage : java AnalisadorLexico [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          // Side-effect: is encodingName valid?
          java.nio.charset.Charset.forName(encodingName);
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        AnalisadorLexico scanner = null;
        java.io.FileInputStream stream = null;
        java.io.Reader reader = null;
        try {
          stream = new java.io.FileInputStream(argv[i]);
          reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new AnalisadorLexico(reader);
          while ( !scanner.zzAtEOF ) scanner.yylex();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
        finally {
          if (reader != null) {
            try {
              reader.close();
            }
            catch (java.io.IOException e) {
              System.out.println("IO error closing file \""+argv[i]+"\"");
              System.out.println(e);
            }
          }
          if (stream != null) {
            try {
              stream.close();
            }
            catch (java.io.IOException e) {
              System.out.println("IO error closing file \""+argv[i]+"\"");
              System.out.println(e);
            }
          }
        }
      }
    }
  }


}
