package src;

public enum TiposDeToken {
    PALAVRA_RESERVADA_PROGRAM,
    PALAVRA_RESERVADA_DECLARE,
    PALAVRA_RESERVADA_READ,
    PALAVRA_RESERVADA_WRITE,
    PALAVRA_RESERVADA_BEGIN,

    PALAVRA_RESERVADA_END,
    PALAVRA_RESERVADA_INTEGER,
    PALAVRA_RESERVADA_DECIMAL,

    PALAVRA_RESERVADA_IF,
    PALAVRA_RESERVADA_THEN,

    PALAVRA_RESERVADA_ELSE,

    PALAVRA_RESERVADA_DO,
    PALAVRA_RESERVADA_WHILE,
    PALAVRA_RESERVADA_FOR,
    PALAVRA_RESERVADA_TO,
    PALAVRA_RESERVADA_NOT,
    PALAVRA_RESERVADA_MOD,
    PALAVRA_RESERVADA_AND,
    PALAVRA_RESERVADA_OR,

    OPERADOR_LESS,
    OPERADOR_GREAT,
    OPERADOR_EQUAL,
    OPERADOR_DIFFERENT,
    OPERADOR_LESSEQUAL,
    OPERADOR_GREATEQUAL,
    OPERADOR_ASSIGN,
    OPERADOR_ADD,
    OPERADOR_MINUS,
    OPERADOR_MULT,
    OPERADOR_PART,
    LITERAL,
    COMMA,
    LEFT_PARENTHESIS,
    RIGHT_PARENTHESIS,
    SEMICOLON,
    CONSTANT,

    IDENTIFICADOR
}
