package src;

public enum TiposDeToken {
    PALAVRA_RESERVADA_INTEGER,
    PALAVRA_RESERVADA_FLOAT,

    PALAVRA_RESERVADA_IF,

    PALAVRA_RESERVADA_ELSE,

    PALAVRA_RESERVADA_WHILE,

    PALAVRA_RESERVADA_BEGIN,

    PALAVRA_RESERVADA_END,

    PALAVRA_RESERVADA_DECLERE,

    PALAVRA_RESERVADA_PROGRAM,

    IDENTIFICADOR,
    NUMERO,
    OPERADOR_ARITMETICO,
    OPERADOR_RELACIONAL,
    OPERADOR_LOGICO,
    DELIMITADOR,
    COMENTARIO,
    CADEIA_DE_CARACTERES,
    CARACTERE,
    ERRO,
    FIM_DE_ARQUIVO
}
